Services:
    - prefix: beep/sender
      uris:    
          - tcp://127.0.0.1:5656
    - prefix: boop/sender
      uris:    
          - tcp://127.0.0.1:5757
# all Webapp settings, other than `port` are passed as parameters
# to the Tornado applicaiton constructor in squidwork.websocket.__main__
Webapp:
    port: 8888
    debug: true
